apiVersion: v1
kind: Service
metadata:
  name: armstrong-py-service
  labels:
    app: armstrong-py
spec:
  type: LoadBalancer
  selector:
    app: armstrong-py
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
